resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/6080
      branches:
        include: ^main$
 
pipelines: 
  - name: Pipeline_S_DockerPush_6080_0017
    configuration:
      environmentVariables:
        readOnly:
          env1: u20-install.jfrog-pipelines.com/docker-local/node
    steps:
      - name: S_DockerBuild_6080_0017
        type: DockerBuild
        execution:
          onStart:
            - echo "Preparing for work..."        
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
        configuration:
          nodePool: u16dynamic
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName:  $env1
          dockerImageTag: latest
          inputResources:
            - name: repo
            
