resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/6080
      branches:
        include: ^main$
  - name: docker_linux
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_linux
      buildNumber: 1
 
pipelines: 
  - name: Pipeline_S_DockerPush_6080_0005
    configuration:
      environmentVariables:
        readOnly:
          env1: rgrsaastest1.jfrogdev.org/docker-local/node
    steps:
      - name: S_DockerBuild_6080_0005
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName:  $env1
          dockerImageTag: latest
          inputResources:
            - name: repo
            
      - name: S_DockerPush_6080_0005
        type: DockerPush
        execution:
          onStart:
            - echo "Preparing for work..."
        configuration:
          nodePool: k8sNodePool
          autoPublishBuildInfo: true
          targetRepository: docker-local
          integrations:
            - name: art_v
          inputSteps:
            - name: S_DockerBuild_6080_0005
          outputResources:
            - name: docker_linux
